authApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from .views import get_loginPage,get_registerPage,get_successPage,get_logout

app_name = "authApp"

urlpatterns = [
    path("", get_loginPage, name="loginPage"),
    path("register/", get_registerPage, name="registerPage"),
    path("success/", get_successPage, name="successPage"),
    path("logout/", get_logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

story9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authApp.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

authApp/models.py
from django.db import models

# Create your models here.

authApp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.decorators import login_required

def get_loginPage(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            request.session["user"] = request.POST["username"]
            return redirect("/success/")
        else:
            messages.error(request,"Incorrect account")

    form = AuthenticationForm()
    return render(request, "authApp/loginPage.html", {"form":form })

def get_registerPage(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            request.session["user"] = request.POST["username"]
            return redirect("/success/")
        else:
            messages.error(request,"Please fill based on requirement")

    form = UserCreationForm()
    return render(request, "authApp/registerPage.html", {"form":form})

def get_logout(request):
    if request.method == "POST":
        logout(request)
    return redirect("authApp:loginPage")

@login_required(login_url="authApp:loginPage")
def get_successPage(request):
    username = request.session.get("user")
    return render(request, "authApp/successPage.html", {"username":username })

authApp/templates/authApp/loginPage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-iqcNtN3rj6Y1HX/R0a3zu3ngmbdwEa9qQGHdkXwSRoiE+Gj71p0UNDSm99LcXiXV" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script>
        $(document).ready(function(){
            $("#id_password").addClass("form-control")
            $("#id_username").addClass("form-control")
        });
    </script>
</head>
<body>
    <div class="card mb-3" style="max-width: 20rem;">
        <div class="card-header">Log-In</div>
        <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger">{{message}}</div>
                {% endfor %}
            {% endif %}
            <form action="{% url 'authApp:loginPage' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button id="submision" type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
        <a id="hyper" href="/register/">I have no account and want to register</a>
    </div>
</body>
</html>

authApp/templates/authApp/registerPage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-iqcNtN3rj6Y1HX/R0a3zu3ngmbdwEa9qQGHdkXwSRoiE+Gj71p0UNDSm99LcXiXV" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script>
        $(document).ready(function(){
            $("#id_password1").addClass("form-control")
            $("#id_password2").addClass("form-control")
            $("#id_username").addClass("form-control")
        });
    </script>
</head>
<body>
    <div class="card card-reg mb-3" style="max-width: 20rem;">
        <div class="card-header">Register</div>
        <div class="card-body">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger">{{message}}</div>
                {% endfor %}
            {% endif %}
            <form action="{% url 'authApp:registerPage' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" id="submision-reg" class="btn btn-primary">Sign-up</button>
            </form>
        </div>
        <a id="hyper" href="{% url 'authApp:loginPage' %}">I already have an account and want to login</a>
    </div>
</body>
</html>

authApp/templates/authApp/successPage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-iqcNtN3rj6Y1HX/R0a3zu3ngmbdwEa9qQGHdkXwSRoiE+Gj71p0UNDSm99LcXiXV" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <h1 id="bam-txt">Hey, {{ username }}. You're</h1>
    <div id="bam">
        <img src="{% static 'bam.jpg' %}" alt="bamboozled">
    </div>
    <form id="red" action="{% url 'authApp:logout' %}"method="POST">
        {% csrf_token %}
        <button id="logout-btn" type="submit" class="btn btn-danger">enough! I'll logout right now!</button>
    </form>
</body>
</html>